### ISSUE TITLE
Save automatic formatting?

### ISSUE THREAD

**Issue by zenoncao** [sxzz/eslint-config-legacy#35]

**Comment by zenoncao** [comment]
No prettier is configured, only ESlint,can be automatically saved

**Comment by sxzz** [comment]
```jsonc
// .vscode/settings.json
{
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  }
}
```

**Comment by pino-cao** [comment]
Thanks for your reply！

![image](https://user-images.githubusercontent.com/47590638/173981475-0a5e3d72-4d06-4a9b-ba27-b0711f1dcb64.png)
![image](https://user-images.githubusercontent.com/47590638/173981490-27a60332-5173-4aab-bbad-a0b36ea37a05.png)
![image](https://user-images.githubusercontent.com/47590638/173981535-64d07ccb-fc28-4208-81dc-dad885ca20e6.png)

This is my configuration，but autosave does not take effect.

**Comment by pino-cao** [comment]
> 



> ```js
> // .vscode/settings.json
> {
>   "editor.codeActionsOnSave": {
>     "source.fixAll.eslint": true
>   }
> }
> ```

Thanks for your reply！

![image](https://user-images.githubusercontent.com/47590638/173981475-0a5e3d72-4d06-4a9b-ba27-b0711f1dcb64.png)
![image](https://user-images.githubusercontent.com/47590638/173981490-27a60332-5173-4aab-bbad-a0b36ea37a05.png)
![image](https://user-images.githubusercontent.com/47590638/173981535-64d07ccb-fc28-4208-81dc-dad885ca20e6.png)

This is my configuration，but autosave does not take effect.
