### ISSUE TITLE
保存自动格式化

### ISSUE THREAD

**Issue by zenoncao** [sxzz/eslint-config-legacy#36]
```jsonc
// .vscode/settings.json
{
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  }
}
```

_Originally posted by @sxzz in https://github.com/sxzz/eslint-config/issues/35#issuecomment-1157170915_

**Comment by zenoncao** [comment]
![image](https://user-images.githubusercontent.com/47590638/173994232-3bab3065-0c16-42e7-86ae-ec0c00f3d125.png)
![image](https://user-images.githubusercontent.com/47590638/173994274-ca6f4969-8ff7-402e-888f-802519792d74.png)
![image](https://user-images.githubusercontent.com/47590638/173994293-40a453fa-bd66-4d39-8eec-c8b99a830a9e.png)
没有配置rules，保存自动格式化没有效果，配置后，有效果了，但是 js 文件没有格式化

**Comment by zenoncao** [comment]
规则需要重新配置？

**Comment by sxzz** [comment]
我的规则是用Prettier来做格式化的，如果想用ESLint进行格式化，建议使用 [antfu 的版本](https://github.com/antfu/eslint-config)

**Comment by pino-cao** [comment]
> 

> 我的规则是用Prettier来做格式化的，如果想用ESLint进行格式化，建议使用 [antfu 的版本](https://github.com/antfu/eslint-config)

**Comment by zenoncao** [comment]
> 我的规则是用Prettier来做格式化的，如果想用ESLint进行格式化，建议使用 [antfu 的版本](https://github.com/antfu/eslint-config)

谢谢！
