### ISSUE TITLE
prettier format bug

### ISSUE THREAD

**Issue by xbmlz** [sxzz/eslint-config-legacy#53]
### Describe the bug

我用vscode格式化的时候出现个别标签格式化错误的现象

```html
<view class="login-action">
  <u-button class="w-600 mb-6" type="primary" @click="phoneLoginHandle"
    >手机号登录</u-button
  >
</view>
```

这是我的 `.prettierrc` 文件

```json
{
  "singleQuote": true,
  "semi": false,
  "arrowParens": "avoid",
  "jsxSingleQuote": true,
  "endOfLine": "lf",
  "trailingComma": "es5"
}

```
这是我的`.vscode/settings.json`文件

```json
{
  "npm.packageManager": "pnpm",
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact",
    "html",
    "vue",
    "json",
    "json5",
    "jsonc",
    "yaml"
  ],
  "eslint.probe": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact",
    "html",
    "vue",
    "json",
    "json5",
    "jsonc",
    "yaml"
  ]
}

```

### Reproduction

如上所述

### System Info

```Shell
node-14
win-10
chrome-100
@sxzz/eslint-config
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
https://prettier.io/docs/en/options.html#html-whitespace-sensitivity

try to `htmlWhitespaceSensitivity: "ignore"`
